### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by AlphaDG** [cstruter/MovieDb#1]
The index.php calls /css/app.css and /js/app.js. Neither folder or file exists. This project is nowhere near operational.

**Comment by cstruter** [comment]
Hi Tom

Its perfectly operational if you run the included build batch file (https://github.com/cstruter/MovieDb/blob/master/build.bat) as described in the two links provided in the [readme](https://github.com/cstruter/MovieDb/blob/master/readme.md) file, http://cstruter.com/blog/392 and http://cstruter.com/blog/395 documents everything in detail (RTFM).

Basically in a nutshell, these two "missing" files will be generated from a [gulp](https://gulpjs.com/) process, so you'll need to have [npm](https://www.npmjs.com/) installed on your machine.

The gulp process can be seen over here:
https://github.com/cstruter/MovieDb/blob/master/app/gulpfile.js, you will notice app.js and app.css being generated via these files, the build tasks:
- Concatenates all the static resources (into the two files) 
- Minifies them

Also note on the PHP side of things I use [composer](https://getcomposer.org/) in a similar fashion as npm, to resolve third party PHP dependencies (like the [doctrine](http://www.doctrine-project.org/projects/orm.html) dependency).

Let me know if you dont come right, but installing npm and running the build file should resolve it for you (it will even download and install gulp for you), npm will resolve all additional dependencies as seen over here: https://github.com/cstruter/MovieDb/blob/master/app/package.json

But ja, obviously I am not going to include / litter third party dependencies into my repository, I would rather fetch them from their various sources.

Christoff
